# Generated by Django 3.1.3 on 2024-11-01 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('calificado', models.BooleanField(default=False)),
                ('estado', models.CharField(blank=True, choices=[('0', 'Suscriptor'), ('1', 'Lead'), ('2', 'Oportunidad'), ('3', 'Cliente')], max_length=20, null=True)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaModificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('sector', models.CharField(blank=True, max_length=50, null=True)),
                ('pais', models.CharField(blank=True, max_length=50, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=50, null=True)),
                ('cantEmpleados', models.IntegerField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, choices=[('0', 'Cliente potencial'), ('1', 'Socio'), ('2', 'Revendedor'), ('3', 'Proveedor')], max_length=20, null=True)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaModificacion', models.DateTimeField(auto_now=True)),
                ('propietario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.cuentausuario')),
            ],
        ),
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('objeto', models.CharField(blank=True, choices=[('0', 'Contacto'), ('1', 'Empresa')], max_length=20, null=True)),
                ('tipo', models.CharField(blank=True, choices=[('0', 'Estática'), ('1', 'Activa')], max_length=20, null=True)),
                ('tamano', models.IntegerField(blank=True, null=True)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaModificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(blank=True, max_length=20, null=True)),
                ('principal', models.BooleanField(default=False)),
                ('contacto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='relaciones.contacto')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='relaciones.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='ListaXEmpresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='relaciones.empresa')),
                ('lista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='relaciones.lista')),
            ],
        ),
        migrations.CreateModel(
            name='ListaXContacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='relaciones.contacto')),
                ('lista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='relaciones.lista')),
            ],
        ),
        migrations.AddField(
            model_name='lista',
            name='lista_x_contacto',
            field=models.ManyToManyField(through='relaciones.ListaXContacto', to='relaciones.Contacto'),
        ),
        migrations.AddField(
            model_name='lista',
            name='lista_x_empresa',
            field=models.ManyToManyField(through='relaciones.ListaXEmpresa', to='relaciones.Empresa'),
        ),
        migrations.AddField(
            model_name='lista',
            name='propietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.cuentausuario'),
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pais', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=100, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('principal', models.BooleanField(default=False)),
                ('contacto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='relaciones.contacto')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='relaciones.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='CuentaRedSocial',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('redSocial', models.CharField(blank=True, choices=[('0', 'Facebook'), ('1', 'Linkedin'), ('2', 'Twitter'), ('3', 'Instagram')], max_length=20, null=True)),
                ('nombreUsuario', models.CharField(blank=True, max_length=50, null=True)),
                ('contacto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='relaciones.contacto')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='relaciones.empresa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='CuentaCorreo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('servicio', models.CharField(blank=True, choices=[('0', 'Google'), ('1', 'Microsoft')], max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
                ('contacto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='relaciones.contacto')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='relaciones.empresa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ContactoXEmpresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='relaciones.contacto')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='relaciones.empresa')),
            ],
        ),
        migrations.AddField(
            model_name='contacto',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='relaciones.empresa'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.persona'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='propietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.cuentausuario'),
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, choices=[('0', 'Nota'), ('1', 'Correo'), ('2', 'Llamada'), ('3', 'Tarea'), ('4', 'Reunion'), ('5', 'Mensaje')], max_length=20, null=True)),
                ('titulo', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('fechaHora', models.DateTimeField(blank=True, null=True)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaModificacion', models.DateTimeField(auto_now=True)),
                ('contacto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='relaciones.contacto')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='relaciones.empresa')),
            ],
        ),
    ]
