# Generated by Django 4.2.7 on 2024-12-13 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('relaciones', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campana',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('tipo', models.CharField(blank=True, choices=[('0', 'Campaña de programa'), ('1', 'Campaña stand-alone')], max_length=20, null=True)),
                ('sponsor', models.CharField(blank=True, max_length=50, null=True)),
                ('presupuesto', models.FloatField(blank=True, null=True)),
                ('inicioVigencia', models.DateTimeField(blank=True, null=True)),
                ('finVigencia', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, choices=[('0', 'No vigente'), ('1', 'Vigente')], max_length=20, null=True)),
                ('fechaCreacion', models.DateTimeField(blank=True, null=True)),
                ('fechaModificacion', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, choices=[('0', 'Gráfico de barras'), ('1', 'Gráfico lineal'), ('2', 'Gráfico circular')], max_length=20, null=True)),
                ('titulo', models.CharField(blank=True, max_length=50, null=True)),
                ('subtitulo', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estrategia',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('tipo', models.CharField(blank=True, choices=[('0', 'Programa'), ('1', 'Campaña stand-alone')], max_length=20, null=True)),
                ('sponsor', models.CharField(blank=True, max_length=50, null=True)),
                ('presupuesto', models.FloatField(blank=True, null=True)),
                ('inicioVigencia', models.DateTimeField(blank=True, null=True)),
                ('finVigencia', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, choices=[('0', 'No vigente'), ('1', 'Vigente')], max_length=20, null=True)),
                ('fechaCreacion', models.DateTimeField(blank=True, null=True)),
                ('fechaModificacion', models.DateTimeField(blank=True, null=True)),
                ('leads', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='relaciones.lista')),
            ],
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('formula', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, choices=[('0', 'Plan'), ('1', 'Programa'), ('2', 'Campaña stand-alone'), ('3', 'Campaña de programa'), ('4', 'Correo'), ('5', 'Publicación'), ('6', 'Página web')], max_length=20, null=True)),
                ('calculoAutomatico', models.BooleanField(default=False)),
                ('automatica', models.BooleanField(default=False)),
                ('fechaCreacion', models.DateTimeField(blank=True, null=True)),
                ('fechaModificacion', models.DateTimeField(blank=True, null=True)),
                ('propietario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.cuentausuario')),
            ],
        ),
        migrations.CreateModel(
            name='Oportunidad',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('tipo', models.CharField(blank=True, choices=[('0', 'Negocio existente'), ('1', 'Nuevo negocio')], max_length=20, null=True)),
                ('etapa', models.CharField(blank=True, choices=[('0', 'Calificación'), ('1', 'Necesidad de análisis'), ('2', 'Propuesta'), ('3', 'Negociación'), ('4', 'Perdida'), ('5', 'Ganada')], max_length=20, null=True)),
                ('importe', models.FloatField(blank=True, null=True)),
                ('inicioVigencia', models.DateTimeField(blank=True, null=True)),
                ('finVigencia', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, choices=[('0', 'No vigente'), ('1', 'Vigente')], max_length=20, null=True)),
                ('fechaCreacion', models.DateTimeField(blank=True, null=True)),
                ('fechaModificacion', models.DateTimeField(blank=True, null=True)),
                ('campana', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.campana')),
            ],
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('entidad', models.CharField(blank=True, max_length=50, null=True)),
                ('propiedad', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo', models.CharField(blank=True, choices=[('0', 'int'), ('1', 'string'), ('2', 'date'), ('3', 'bool'), ('4', 'double')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('idUsuario', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('tipo', models.CharField(blank=True, choices=[('0', 'Correo'), ('1', 'Publicación'), ('2', 'Página web')], max_length=20, null=True)),
                ('presupuesto', models.FloatField(blank=True, null=True)),
                ('inicioVigencia', models.DateTimeField(blank=True, null=True)),
                ('finVigencia', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, choices=[('0', 'No vigente'), ('1', 'Vigente')], max_length=20, null=True)),
                ('fechaPublicacion', models.DateTimeField(blank=True, null=True)),
                ('asuntoCorreo', models.TextField(blank=True, null=True)),
                ('remitenteCorreo', models.CharField(blank=True, max_length=50, null=True)),
                ('remitenteContrasena', models.TextField(blank=True, null=True)),
                ('servicioRedSocial', models.CharField(blank=True, choices=[('0', 'Facebook'), ('1', 'Linkedin'), ('2', 'Instagram')], max_length=20, null=True)),
                ('usuarioRedSocial', models.CharField(blank=True, max_length=50, null=True)),
                ('audienciaRedSocial', models.CharField(blank=True, choices=[('0', 'Público en general'), ('1', 'Seguidores')], max_length=20, null=True)),
                ('tokenRedSocial', models.TextField(blank=True, null=True)),
                ('paginaIdRedSocial', models.TextField(blank=True, null=True)),
                ('titulo', models.TextField(blank=True, null=True)),
                ('dominio', models.TextField(blank=True, null=True)),
                ('complementoDominio', models.TextField(blank=True, null=True)),
                ('contenido', models.TextField(blank=True, null=True)),
                ('contenidoHTML', models.TextField(blank=True, null=True)),
                ('fechaCreacion', models.DateTimeField(blank=True, null=True)),
                ('fechaModificacion', models.DateTimeField(blank=True, null=True)),
                ('campana', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.campana')),
                ('propietario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.cuentausuario')),
            ],
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('abreviatura', models.CharField(blank=True, max_length=10, null=True)),
                ('tipo', models.CharField(blank=True, choices=[('0', 'Plan'), ('1', 'Programa'), ('2', 'Campaña stand-alone'), ('3', 'Campaña de programa'), ('4', 'Correo'), ('5', 'Publicación'), ('6', 'Página web')], max_length=20, null=True)),
                ('automatica', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VariableXIndicador',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('indicador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketing.indicador')),
                ('variable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketing.variable')),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('tipo', models.CharField(blank=True, choices=[('0', 'Plan'), ('1', 'Programa'), ('2', 'Campaña'), ('3', 'Recurso'), ('4', 'Oportunidad'), ('5', 'Contacto'), ('6', 'Empresa')], max_length=20, null=True)),
                ('fechaCreacion', models.DateTimeField(blank=True, null=True)),
                ('fechaModificacion', models.DateTimeField(blank=True, null=True)),
                ('propietario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.cuentausuario')),
            ],
        ),
        migrations.CreateModel(
            name='RecursoXContacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='relaciones.contacto')),
                ('recurso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketing.recurso')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('sponsor', models.CharField(blank=True, max_length=50, null=True)),
                ('presupuesto', models.FloatField(blank=True, null=True)),
                ('inicioVigencia', models.DateTimeField(blank=True, null=True)),
                ('finVigencia', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, choices=[('0', 'No vigente'), ('1', 'Vigente')], max_length=20, null=True)),
                ('fechaCreacion', models.DateTimeField(blank=True, null=True)),
                ('fechaModificacion', models.DateTimeField(blank=True, null=True)),
                ('propietario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.cuentausuario')),
            ],
        ),
        migrations.CreateModel(
            name='OportunidadXContacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='relaciones.contacto')),
                ('oportunidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketing.oportunidad')),
            ],
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='oportunidad_x_contacto',
            field=models.ManyToManyField(through='marketing.OportunidadXContacto', to='relaciones.contacto'),
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='propietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.cuentausuario'),
        ),
        migrations.CreateModel(
            name='IndicadorAsignado',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('valor', models.FloatField(blank=True, null=True)),
                ('campana', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketing.campana')),
                ('estrategia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketing.estrategia')),
                ('indicador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketing.indicador')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketing.plan')),
                ('recurso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketing.recurso')),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('contenido', models.TextField(blank=True, null=True)),
                ('enlace', models.TextField(blank=True, null=True)),
                ('recurso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.recurso')),
            ],
        ),
        migrations.CreateModel(
            name='Flujo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('contenido', models.TextField(blank=True, null=True)),
                ('fechaCreacion', models.DateTimeField(blank=True, null=True)),
                ('fechaModificacion', models.DateTimeField(blank=True, null=True)),
                ('propietario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.cuentausuario')),
            ],
        ),
        migrations.CreateModel(
            name='Filtro',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('entidad', models.CharField(blank=True, max_length=200, null=True)),
                ('propiedad', models.CharField(blank=True, max_length=200, null=True)),
                ('evaluacion', models.CharField(blank=True, choices=[('0', 'Igual'), ('1', 'Menor'), ('2', 'Mayor'), ('3', 'Menor o igual'), ('4', 'Mayor o igual'), ('5', 'Contiene')], max_length=20, null=True)),
                ('valorEvaluacion', models.CharField(blank=True, max_length=200, null=True)),
                ('lista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='relaciones.lista')),
                ('reporte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketing.reporte')),
            ],
        ),
        migrations.CreateModel(
            name='Fila',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('contenido', models.TextField(blank=True, null=True)),
                ('reporte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.reporte')),
            ],
        ),
        migrations.AddField(
            model_name='estrategia',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.plan'),
        ),
        migrations.AddField(
            model_name='estrategia',
            name='propietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.cuentausuario'),
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('principal', models.BooleanField(default=False)),
                ('fechaCreacion', models.DateTimeField(blank=True, null=True)),
                ('fechaModificacion', models.DateTimeField(blank=True, null=True)),
                ('propietario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.cuentausuario')),
            ],
        ),
        migrations.CreateModel(
            name='ComponenteLabel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, max_length=50, null=True)),
                ('componente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.componente')),
            ],
        ),
        migrations.CreateModel(
            name='ComponenteCantidad',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad', models.FloatField(blank=True, null=True)),
                ('componente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.componente')),
            ],
        ),
        migrations.AddField(
            model_name='componente',
            name='dashboard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.dashboard'),
        ),
        migrations.CreateModel(
            name='Columna',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('reporte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.reporte')),
            ],
        ),
        migrations.CreateModel(
            name='CampanaXContacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campana', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketing.campana')),
                ('contacto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='relaciones.contacto')),
            ],
        ),
        migrations.AddField(
            model_name='campana',
            name='estrategia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.estrategia'),
        ),
        migrations.AddField(
            model_name='campana',
            name='leads',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='relaciones.lista'),
        ),
        migrations.AddField(
            model_name='campana',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.plan'),
        ),
        migrations.AddField(
            model_name='campana',
            name='propietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.cuentausuario'),
        ),
    ]
