# Generated by Django 3.1.3 on 2024-11-01 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('relaciones', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campana',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('presupuesto', models.FloatField(blank=True, null=True)),
                ('inicioVigencia', models.DateTimeField(blank=True, null=True)),
                ('finVigencia', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, choices=[('0', 'No vigente'), ('1', 'Vigente')], max_length=20, null=True)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaModificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estrategia',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('tipo', models.CharField(blank=True, choices=[('0', 'Programa'), ('1', 'Campaña stand-alone')], max_length=20, null=True)),
                ('sponsor', models.CharField(blank=True, max_length=50, null=True)),
                ('presupuesto', models.FloatField(blank=True, null=True)),
                ('inicioVigencia', models.DateTimeField(blank=True, null=True)),
                ('finVigencia', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, choices=[('0', 'No vigente'), ('1', 'Vigente')], max_length=20, null=True)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaModificacion', models.DateTimeField(auto_now=True)),
                ('leads', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='relaciones.lista')),
            ],
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('formula', models.TextField(blank=True, null=True)),
                ('aspecto', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('automatica', models.BooleanField(default=False)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaModificacion', models.DateTimeField(auto_now=True)),
                ('propietario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.cuentausuario')),
            ],
        ),
        migrations.CreateModel(
            name='Oportunidad',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('tipo', models.CharField(blank=True, choices=[('0', 'Negocio existente'), ('1', 'Nuevo negocio')], max_length=20, null=True)),
                ('etapa', models.CharField(blank=True, choices=[('0', 'Calificación'), ('1', 'Necesidad de análisis'), ('2', 'Propuesta'), ('3', 'Negociación'), ('4', 'Perdida'), ('5', 'Ganada')], max_length=20, null=True)),
                ('importe', models.FloatField(blank=True, null=True)),
                ('inicioVigencia', models.DateTimeField(blank=True, null=True)),
                ('finVigencia', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, choices=[('0', 'No vigente'), ('1', 'Vigente')], max_length=20, null=True)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaModificacion', models.DateTimeField(auto_now=True)),
                ('campanaAsociada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.campana')),
                ('campanaStandAloneAsociada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.estrategia')),
            ],
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('entidad', models.CharField(blank=True, max_length=50, null=True)),
                ('propiedad', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo', models.CharField(blank=True, choices=[('0', 'int'), ('1', 'string'), ('2', 'date'), ('3', 'bool'), ('4', 'double')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('abreviatura', models.CharField(blank=True, max_length=10, null=True)),
                ('aspecto', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('automatica', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VariableXIndicador',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('indicador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketing.indicador')),
                ('variable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketing.variable')),
            ],
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('tipo', models.CharField(blank=True, choices=[('0', 'Correo'), ('1', 'Publicación'), ('2', 'Página web')], max_length=20, null=True)),
                ('presupuesto', models.FloatField(blank=True, null=True)),
                ('inicioVigencia', models.DateTimeField(blank=True, null=True)),
                ('finVigencia', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, choices=[('0', 'No vigente'), ('1', 'Vigente')], max_length=20, null=True)),
                ('fechaPublicacion', models.DateTimeField(blank=True, null=True)),
                ('asunto', models.TextField(blank=True, null=True)),
                ('audiencia', models.TextField(blank=True, null=True)),
                ('dominio', models.TextField(blank=True, null=True)),
                ('complementoDominio', models.TextField(blank=True, null=True)),
                ('contenido', models.TextField(blank=True, null=True)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaModificacion', models.DateTimeField(auto_now=True)),
                ('campana', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.campana')),
                ('estrategia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.estrategia')),
                ('propietario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.cuentausuario')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('sponsor', models.CharField(blank=True, max_length=50, null=True)),
                ('presupuesto', models.FloatField(blank=True, null=True)),
                ('inicioVigencia', models.DateTimeField(blank=True, null=True)),
                ('finVigencia', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, choices=[('0', 'No vigente'), ('1', 'Vigente')], max_length=20, null=True)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaModificacion', models.DateTimeField(auto_now=True)),
                ('propietario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.cuentausuario')),
            ],
        ),
        migrations.CreateModel(
            name='OportunidadXContacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='relaciones.contacto')),
                ('oportunidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketing.oportunidad')),
            ],
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='oportunidad_x_contacto',
            field=models.ManyToManyField(through='marketing.OportunidadXContacto', to='relaciones.Contacto'),
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='propietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.cuentausuario'),
        ),
        migrations.CreateModel(
            name='IndicadorAsignado',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('calculoAutomatico', models.BooleanField(default=False)),
                ('campana', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketing.campana')),
                ('estrategia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketing.estrategia')),
                ('indicador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketing.indicador')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketing.plan')),
                ('recurso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketing.recurso')),
            ],
        ),
        migrations.CreateModel(
            name='Filtro',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('evaluacion', models.CharField(blank=True, choices=[('0', 'Igual'), ('1', 'Menor'), ('2', 'Mayor'), ('3', 'Menor o igual'), ('4', 'Mayor o igual'), ('5', 'Diferente'), ('6', 'Contiene'), ('7', 'No contiene')], max_length=20, null=True)),
                ('valorEvaluacion', models.CharField(blank=True, max_length=200, null=True)),
                ('lista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='relaciones.lista')),
                ('propiedad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketing.propiedad')),
            ],
        ),
        migrations.AddField(
            model_name='estrategia',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.plan'),
        ),
        migrations.AddField(
            model_name='estrategia',
            name='propietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.cuentausuario'),
        ),
        migrations.AddField(
            model_name='campana',
            name='estrategia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.estrategia'),
        ),
        migrations.AddField(
            model_name='campana',
            name='leads',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='relaciones.lista'),
        ),
        migrations.AddField(
            model_name='campana',
            name='propietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.cuentausuario'),
        ),
    ]
