# Generated by Django 4.2.7 on 2024-12-13 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, choices=[('0', 'Actividad'), ('1', 'Error')], max_length=20, null=True)),
                ('codigo', models.CharField(blank=True, max_length=100, null=True)),
                ('fuente', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('fechaHora', models.DateTimeField(blank=True, null=True)),
                ('propietario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.cuentausuario')),
            ],
        ),
    ]
